image: python:3.11

services:
  - name: neo4j:5
    alias: neo4j

variables:
  NEO4J_AUTH: "neo4j/password"
  NEO4J_URI: "bolt://neo4j:7687"
  NEO4J_USERNAME: "neo4j"
  NEO4J_PASSWORD: "password"
  NEO4J_DATABASE: "neo4j"
  PYTHONPATH: "$CI_PROJECT_DIR/backend"

before_script:
  - pip install --upgrade pip
  - pip install -r backend/requirements.txt

test:
  script:
    - echo " Attente de 20 secondes pour que Neo4j démarre..."
    - sleep 20
    - cd backend
    - pytest --html=report.html --self-contained-html tests/
  artifacts:
    paths:
      - backend/report.html
