image: python:3.11

services:
  - name: neo4j:5
    alias: neo4j
    entrypoint: ["/bin/bash", "-c"]
    command: ["neo4j-admin dbms set-initial-password test && neo4j console"]


variables:
  NEO4J_URI: "bolt://neo4j:7687"
  NEO4J_USERNAME: "neo4j"
  NEO4J_PASSWORD: "test"
  NEO4J_DATABASE: "neo4j"
  PYTHONDONTWRITEBYTECODE: "1"
  PYTHONUNBUFFERED: "1"

before_script:
  - pip install --upgrade pip
  - pip install -r backend/requirements.txt
  - cd backend
  - export PYTHONPATH=$(pwd)

test:
  stage: test
  script:
    - cd backend
    - pytest tests/
