image: python:3.11

services:
  - name: neo4j:5
    alias: neo4j

variables:
  NEO4J_USERNAME: neo4j
  NEO4J_PASSWORD: password


before_script:
  - pip install -r backend/requirements.txt

test:
  script:
    - cd backend
    - pytest tests/
    - export PYTHONPATH=$(pwd)
  
