image: python:3.11

services:
  - name: neo4j:5
    alias: neo4j

variables:
  NEO4J_AUTH: "neo4j/password"
  NEO4J_URI: "bolt://neo4j:7687"
  NEO4J_USERNAME: "neo4j"
  NEO4J_PASSWORD: "password"
  NEO4J_DATABASE: "neo4j"
  PYTHONPATH: "$CI_PROJECT_DIR/backend"

before_script:
  - pip install --upgrade pip
  - pip install -r backend/requirements.txt

test:
  script:
    - cd backend
    - pytest tests/
