image: python:3.11
services:
  - name: neo4j:5
    alias: neo4j
    entrypoint: ["/bin/bash", "-c"]
    command: ["neo4j-admin dbms set-initial-password 'MyStrongPassword!' && neo4j"]

variables:
  NEO4J_URI: bolt://neo4j:7687
  NEO4J_USERNAME: neo4j
  NEO4J_PASSWORD: MyStrongPassword!
  NEO4J_DATABASE: neo4j

stages:
  - test

test:
  image: python:3.11
  stage: test
  before_script:
    - pip install --upgrade pip
    - pip install -r backend/requirements.txt
  script:
    - cd backend
    - export PYTHONPATH=$(pwd)
    - pytest tests/
