image: python:3.11

services:
  - name: neo4j:5
    alias: neo4j
    entrypoint: ["/bin/bash", "-c"]
    command: ["neo4j-admin set-initial-password password && neo4j console"]

variables:
  NEO4J_URI: bolt://neo4j:7687
  NEO4J_USERNAME: neo4j
  NEO4J_PASSWORD: password

before_script:
  - pip install -r backend/requirements.txt

test:
  script:
    - cd backend
    - export PYTHONPATH=$(pwd)
    - pytest tests/
