image: python:3.11

services:
  - name: neo4j:5
    alias: neo4j
    entrypoint: ["/bin/bash", "-c"]
    command: ["neo4j-admin dbms set-initial-password admin1234 && neo4j console"]

variables:
  NEO4J_URI: bolt://neo4j:7687
  NEO4J_USERNAME: neo4j
  NEO4J_PASSWORD: admin1234
  NEO4J_DATABASE: neo4j

before_script:
  - pip install --upgrade pip
  - pip install -r backend/requirements.txt

test_backend:
  stage: test
  script:
    - cd backend
    - export PYTHONPATH=$(pwd)
    - pytest tests/
