stages:
  - test

test_backend:
  stage: test
  image: python:3.11
  services:
    - name: neo4j:5
      alias: neo4j
  variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
    NEO4J_URI: "bolt://neo4j:7687"
    NEO4J_USERNAME: "neo4j"
    NEO4J_PASSWORD: "password"
  before_script:
    - python -m pip install --upgrade pip
    - pip install -r requirements.txt
  script:
    - pytest tests/
