import { Injectable } from "@angular/core";
import { Formation } from "../models/formation.model";
import { Observable, of } from 'rxjs';

@Injectable({
    providedIn: 'root'
})
export class FormationService {
    private formations: Formation[] = [
        new Formation(
            "1", 
            "2024", 
            "Public",
            "5464", 
            "Université de Bourgogne", 
            "21000", 
            "Côte-D'Or", 
            "Bourgogne - Franche Comté", 
            "48.8566,2.3522", 
            "Académie de Dijon", 
            "Sélective",
            "Licence Informatique",
            "Licence", 
            "Bases de données & Intelligence artificielle", 
            "Général", 
            "Mathématiques avancées", 
            "https://parcoursup.fr/formation1", 
            "300", 
            "1250", 
            "266", 
            "294", 
            "25", 
            "20", 
            "555", 
            "645", 
            "10", 
            "20", 
            "100", 
            "200", 
            "50", 
            "70", 
            "20", 
            "80", 
            "10", 
            "20", 
            "15", 
            "10", 
            "298", 
            "39", 
            "15", 
            "10", 
            "",
            "",
            "50", 
            "30", 
            "15", 
            "40", 
            "45", 
            "30", 
            "20",
            "",
            "",
            "",
            "",
            "548",
            "5454",
            "54450",
            "545",
            "9"
        ),
        new Formation(
            "2", 
            "2024", 
            "Actif", 
            "123457", 
            "Lycée B", 
            "69", 
            "Lyon", 
            "Auvergne-Rhône-Alpes", 
            "45.7640,4.8357", 
            "Académie de Lyon", 
            "Non sélective", 
            "Lettres", 
            "Littérature", 
            "Détails approfondis des lettres", 
            "Humanités", 
            "Littérature comparée", 
            "https://parcoursup.fr/formation2", 
            "50", 
            "150", 
            "80", 
            "100", 
            "60", 
            "10", 
            "20", 
            "10", 
            "5", 
            "15", 
            "50", 
            "150", 
            "5", 
            "15", 
            "10", 
            "40", 
            "12", 
            "18", 
            "8", 
            "6", 
            "50", 
            "20", 
            "10", 
            "15", 
            "25", 
            "35", 
            "30", 
            "15", 
            "20", 
            "18"
        ),
        new Formation(
            "3", 
            "2024", 
            "Actif", 
            "123458", 
            "Université C", 
            "13", 
            "Marseille", 
            "Provence-Alpes-Côte d'Azur", 
            "43.2965,5.3698", 
            "Académie d'Aix-Marseille", 
            "Sélective", 
            "Droit", 
            "Droit civil", 
            "Détails avancés du droit civil", 
            "Juridique", 
            "Droit constitutionnel", 
            "https://parcoursup.fr/formation3", 
            "40", 
            "180", 
            "90", 
            "130", 
            "80", 
            "15", 
            "25", 
            "20", 
            "7", 
            "18", 
            "70", 
            "180", 
            "6", 
            "20", 
            "12", 
            "50", 
            "12", 
            "30", 
            "15", 
            "8", 
            "40", 
            "18", 
            "10", 
            "20", 
            "28", 
            "25", 
            "30", 
            "12", 
            "18",
            "23","5",'564','2454','54548','5454','5448','4',
            "180", 
            "6", 
            "20", 
            "12", 
            "50", 
            "12", 
            "30", 
            "15", 
            "8", 
            "40","445"
        ),
        new Formation(
            "4", 
            "2024", 
            "Actif", 
            "123459", 
            "Université D", 
            "31", 
            "Toulouse", 
            "Occitanie", 
            "43.6045,1.4442", 
            "Académie de Toulouse", 
            "Non sélective", 
            "Médecine", 
            "Pharmacie", 
            "Détails sur les sciences pharmaceutiques", 
            "Santé", 
            "Pharmacologie avancée", 
            "https://parcoursup.fr/formation4", 
            "60", 
            "300", 
            "150", 
            "200", 
            "120", 
            "30", 
            "40", 
            "30", 
            "12", 
            "28", 
            "90", 
            "300", 
            "10", 
            "35", 
            "18", 
            "75", 
            "20", 
            "50", 
            "40", 
            "15", 
            "100", 
            "25", 
            "18", 
            "25", 
            "35", 
            "40", 
            "50", 
            "30", 
            "40", 
            "50"
        ),
        new Formation(
            "5", 
            "2024", 
            "Actif", 
            "123460", 
            "École E", 
            "59", 
            "Lille", 
            "Hauts-de-France", 
            "50.6292,3.0573", 
            "Académie de Lille", 
            "Sélective", 
            "Sciences", 
            "Chimie", 
            "Détails approfondis de la chimie", 
            "Technologique", 
            "Chimie moléculaire", 
            "https://parcoursup.fr/formation5", 
            "25", 
            "100", 
            "50", 
            "80", 
            "50", 
            "10", 
            "15", 
            "10", 
            "5", 
            "10", 
            "40", 
            "100", 
            "5", 
            "20", 
            "10", 
            "35", 
            "8", 
            "12", 
            "6", 
            "3", 
            "30", 
            "12", 
            "8", 
            "10", 
            "15", 
            "20", 
            "25", 
            "15", 
            "20", 
            "28"
        )
    ];

    getAllFormations(): Observable<Formation[]> {
      return of([...this.formations]);
    }
  
    getFormationByID(id: string): Formation {
      const foundFormation: Formation | undefined = this.formations.find(formation => formation.id === id);
  
      if (!foundFormation) {
        throw new Error('Formation inconnue !');
      }
  
      return foundFormation;
    }
}
